### ISSUE TITLE
calling numberfield from a button

### ISSUE THREAD

**Issue by dpalme3160** [KennethTsang/NumberField#1]
In a previous discussion with you, you suggested calling numberField.becomeFirstResponder() but that is throwing an error: "use of instance member 'becomeFirstResponder' on type 'numberField'...

Suggestions?

**Comment by KennethTsang** [comment]
You need to call on an instance, not the type.

**Comment by dpalme3160** [comment]
Ok, I'm a little weak on this sorry.

I have the following:
tipAmount.becomeFirstResponder()

its throwing a warning now: "Result of call to 'becomeFirstResponder()' is unused.  Not sure what else I need to be doing here.

**Comment by KennethTsang** [comment]
Try this:
`let _ = tipAmount.becomeFirstResponder() `

**Comment by dpalme3160** [comment]
One follow up question, is there a way to add a done button to your numeric pad.

**Comment by KennethTsang** [comment]
It is a good idea, what is the best position to place the done button u think?

**Comment by dpalme3160** [comment]
I'd love to see it upper right hand corner just above the actual numeric pad.
